PomoćniProjekatGamingHub/Controllers/ModeratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PomoćniProjekatGamingHub.EF;
using PomoćniProjekatGamingHub.EntityModels;
using PomoćniProjekatGamingHub.Models.Konzola;
using PomoćniProjekatGamingHub.Models.Zarn;

namespace PomoćniProjekatGamingHub.Controllers
{
    public class ModeratorController : Controller
    {
        MojDbContext db = new MojDbContext();
        public IActionResult KonzolaPrikaz()
        {
            var m = db.Konzola.Select(k => new KonzolaPrikazVM
            {
                Id = k.Id,
                Kapacitet = k.Kapacitet,
                Detalji = k.Detalji,
                Naziv = k.Naziv,
                Proizvodjac = k.Proizvodjac
            }).ToList();

            return View(m);
        }
        public IActionResult UrediKonzolu(int KonzolaID)
        {
            KonzolaUrediVM m;
            if (KonzolaID == 0)
            {
                m = new KonzolaUrediVM() { };
            }
            else
            {
                m = db.Konzola.Where(k => k.Id == KonzolaID)
                .Select(k => new KonzolaUrediVM
                {
                    KonzolaID = k.Id,
                    Naziv = k.Naziv,
                    Detalji = k.Detalji,
                    Kapacitet = k.Kapacitet,
                    Proizvodjac = k.Proizvodjac
                }).Single();
            }
            return View(m);
        }
        public IActionResult SnimiKonzolu(KonzolaUrediVM Konzola)
        {
             Konzola konzola;
            if (Konzola.KonzolaID == 0)
            {
                konzola = new Konzola();
                db.Add(konzola);
            }
            else
            {
                konzola = db.Konzola.Find(Konzola.KonzolaID);
            }
            konzola.Naziv = Konzola.Naziv;
            konzola.Proizvodjac = Konzola.Proizvodjac;
            konzola.Kapacitet = Konzola.Kapacitet;
            konzola.Detalji = Konzola.Detalji;

            db.SaveChanges();
            return Redirect("/Moderator/KonzolaPrikaz");
        }
        public IActionResult ObrisiKonzolu(int KonzolaID)
        {
             Konzola k = db.Konzola.Find(KonzolaID);
            db.Remove(k);
            db.SaveChanges();
            return Redirect("/Moderator/KonzolaPrikaz");
        }
        public IActionResult ListaRecenzija()
        {
             List<Recenzija> recenzije = db.Recenzija.ToList();
            ViewData["recenzije"] = recenzije;
            return View("ListaRecenzija");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

PomoćniProjekatGamingHub/Views/Moderator/KonzolaPrikaz.cshtml
@using PomoćniProjekatGamingHub.Models.Konzola
@model  List<KonzolaPrikazVM>
<h1>KonzolaPrikaz</h1>

<a href="/Moderator/UrediKonzolu" class="btn btn-success">Dodaj</a>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Opis</th>
            <th>Kapacitet</th>
            <th>Detalji</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (KonzolaPrikazVM k in Model)
        {
            <tr>
                <td>@k.Naziv</td>
                <td>@k.Proizvodjac</td>
                <td>@k.Kapacitet</td>
                <td>@k.Detalji</td>
                <td>
                    <a href="/Moderator/UrediKonzolu?KonzolaID=@k.Id" class="btn btn-primary">Uredi</a>
                    <a href="/Moderator/ObrisiKonzolu?KonzolaID=@k.Id" class="btn btn-danger">Obrisi</a>
                </td>
            </tr>
        }

    </tbody>
</table>

PomoćniProjekatGamingHub/Views/Moderator/ListaIgara.cshtml
@using PomoćniProjekatGamingHub.EntityModels

@{
    var igre = (List<Igra>)ViewData["igre"];
}

<h1>Igre</h1>
<a href="/Moderator/UrediIgru" class="btn btn-success">Dodaj</a>

<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>Slika</th>
            <th>Naziv</th>
            <th>Izdavac</th>
            <th>Developer</th>
            <th>Datum Izlaska</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Igra i in igre)
        {
            <tr>
                <td>@i.SlikaLink</td>
                <td>@i.Naziv</td>
                <td>@i.Izdavac</td>
                <td>@i.Developer</td>
                <td>@i.DatumIzlaska</td>
                <td>
                    <a href="/Moderator/DetaljiIgre?IgraID=@i.Id" class="btn btn-primary">Detalji</a>
                    <a href="/Moderator/UrediIgru?IgraID=@i.Id" class="btn btn-primary">Uredi</a>
                    <a href="/Moderator/ObrisiIgru?IgraID=@i.Id" class="btn btn-danger">Obrisi</a>
                </td>
            </tr>
        }

    </tbody>
</table>

PomoćniProjekatGamingHub/Views/Moderator/ListaRecenzija.cshtml
@using PomoćniProjekatGamingHub.EntityModels

@{
    var recenzije = (List<Recenzija>)ViewData["recenzije"];
}

<div class="container">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="my-4">
                Page Heading
                <small>Secondary Text</small>
            </h1>
            <br />
            <a href="/Moderator/UrediRecenziju" class="btn btn-success">Dodaj recenziju</a>
            <br />
            <!-- Blog Recenzija -->
            @foreach (Recenzija r in recenzije)
            {
                <div class="card mb-4">
                    <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title">@r.Naslov</h2>
                        <p class="card-text">@r.Sadrzaj</p>
                        <a href="/Moderator/Detalji" class="btn btn-primary">Procitaj vise &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        <a href="#"> @r.Korisnik.KorisnickoIme </a> @r.DatumKreiranja
                    </div>
                </div>
            }

        </div>
    </div>
</div>

PomoćniProjekatGamingHub/Views/Moderator/PrikazZarn.cshtml
@using PomoćniProjekatGamingHub.Models.Zarn

@model List<ZarnPrikazVM>

<h1>Zarnovi</h1>
<a href="/Moderator/UrediZarn" class="btn btn-success">Dodaj</a>
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Opis</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (ZarnPrikazVM z in Model)
        {
            <tr>
                <td>@z.Naziv</td>
                <td>@z.Opis</td>
                <td>
                    <a href="/Moderator/UrediZarn?ZarnID=@z.Id" class="btn btn-primary">Uredi</a>
                    <a href="/Moderator/Obrisi?ZarnID=@z.Id" class="btn btn-danger">Obrisi</a>
                </td>
            </tr>
        }

    </tbody>
</table>

PomoćniProjekatGamingHub/Views/Moderator/UrediKonzolu.cshtml
@model PomoćniProjekatGamingHub.Models.Konzola.KonzolaUrediVM


<h1>UrediKonzolu</h1>

<h4>Konzola</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SnimiKonzolu" asp-controller="Moderator">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" readonly style="display:none">
                <label>KonzolaID</label>
                <input name="KonzolaID" value="@Model.KonzolaID" class="form-control" />
                <span asp-validation-for="KonzolaID" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" value="@Model.Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Proizvodjac" class="control-label"></label>
                <input asp-for="Proizvodjac" value="@Model.Proizvodjac" class="form-control" />
                <span asp-validation-for="Proizvodjac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kapacitet" class="control-label"></label>
                <input asp-for="Kapacitet" value="@Model.Kapacitet" class="form-control" />
                <span asp-validation-for="Kapacitet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detalji" class="control-label"></label>
                <input asp-for="Detalji" value="@Model.Detalji" class="form-control" />
                <span asp-validation-for="Detalji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="SnimiKonzolu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="KonzolaPrikaz">Nazad na listu</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PomoćniProjekatGamingHub/Views/Moderator/UrediZarn.cshtml
@model PomoćniProjekatGamingHub.Models.Zarn.ZarnUrediVM

<h1>UrediZarn</h1>

<h4>Zarn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SnimiZarn" asp-controller="Moderator">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" readonly style="display:none">
                <label>ZarnID</label>
                <input name="Id" value="@Model.Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Naziv"  class="control-label"></label>
                <input asp-for="Naziv" value=@Model.Naziv class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" value=@Model.Opis class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Snimi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="PrikazZarn">Nazad na listu</a>
</div>