PomoćniProjekatGamingHub/Models/Konzola/KonzolaPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PomoćniProjekatGamingHub.Models.Konzola
{
    public class KonzolaPrikazVM
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public int Kapacitet { get; set; }
        public string Detalji { get; set; }
    }
}

PomoćniProjekatGamingHub/Models/Konzola/KonzolaUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PomoćniProjekatGamingHub.Models.Konzola
{
    public class KonzolaUrediVM
    {
        public int KonzolaID { get; set; }
        public string Naziv { get; set; }
        public int Kapacitet { get; set; }
        public string Detalji { get; set; }
    }
}

PomoćniProjekatGamingHub/Controllers/KonzolaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PomoćniProjekatGamingHub.EF;
using PomoćniProjekatGamingHub.EntityModels;
using PomoćniProjekatGamingHub.Models.Konzola;
using PomoćniProjekatGamingHub.Models.Zarn;

namespace PomoćniProjekatGamingHub.Controllers
{
    public class KonzolaController : Controller
    {
        MojDbContext db = new MojDbContext();
        public IActionResult Prikaz()
        {
            var m = db.Konzola.Select(k => new KonzolaPrikazVM
            {
                Id = k.Id,
                Kapacitet = k.Kapacitet,
                Detalji = k.Detalji,
                Naziv = k.Naziv,
            }).ToList();

            return View(m);
        }
        public IActionResult Uredi(int KonzolaID)
        {
            KonzolaUrediVM m;
            if (KonzolaID == 0)
            {
                m = new KonzolaUrediVM() { };
            }
            else
            {
                m = db.Konzola.Where(k => k.Id == KonzolaID)
                .Select(k => new KonzolaUrediVM
                {
                    KonzolaID = k.Id,
                    Naziv = k.Naziv,
                    Detalji = k.Detalji,
                    Kapacitet = k.Kapacitet,
                }).Single();
            }
            return View(m);
        }
        public IActionResult Snimi(KonzolaUrediVM Konzola)
        {
             Konzola konzola;
            if (Konzola.KonzolaID == 0)
            {
                konzola = new Konzola();
                db.Add(konzola);
            }
            else
            {
                konzola = db.Konzola.Find(Konzola.KonzolaID);
            }
            konzola.Naziv = Konzola.Naziv;
            konzola.Kapacitet = Konzola.Kapacitet;
            konzola.Detalji = Konzola.Detalji;

            db.SaveChanges();
            return Redirect("/Konzola/Prikaz");
        }
        public IActionResult Obrisi(int KonzolaID)
        {
             Konzola k = db.Konzola.Find(KonzolaID);
            db.Remove(k);
            db.SaveChanges();
            return Redirect("/Konzola/Prikaz");
        }
        public IActionResult ListaRecenzija()
        {
             List<Recenzija> recenzije = db.Recenzija.ToList();
            ViewData["recenzije"] = recenzije;
            return View("ListaRecenzija");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

PomoćniProjekatGamingHub/Views/Konzola/Prikaz.cshtml
@using PomoćniProjekatGamingHub.Models.Konzola
@model  List<KonzolaPrikazVM>
<h1>KonzolaPrikaz</h1>

<a href="/Konzola/Uredi" class="btn btn-success">Dodaj</a>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Kapacitet</th>
            <th>Detalji</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (KonzolaPrikazVM k in Model)
        {
            <tr>
                <td>@k.Naziv</td>
                <td>@k.Kapacitet</td>
                <td>@k.Detalji</td>
                <td>
                    <a href="/Konzola/Uredi?KonzolaID=@k.Id" class="btn btn-primary">Uredi</a>
                    <a href="/Konzola/Obrisi?KonzolaID=@k.Id" class="btn btn-danger">Obrisi</a>
                </td>
            </tr>
        }

    </tbody>
</table>

PomoćniProjekatGamingHub/Views/Konzola/Uredi.cshtml
@model PomoćniProjekatGamingHub.Models.Konzola.KonzolaUrediVM


<h1>UrediKonzolu</h1>

<h4>Konzola</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Snimi" asp-controller="Konzola">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" readonly style="display:none">
                <label>KonzolaID</label>
                <input name="KonzolaID" value="@Model.KonzolaID" class="form-control" />
                <span asp-validation-for="KonzolaID" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" value="@Model.Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kapacitet" class="control-label"></label>
                <input asp-for="Kapacitet" value="@Model.Kapacitet" class="form-control" />
                <span asp-validation-for="Kapacitet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detalji" class="control-label"></label>
                <input asp-for="Detalji" value="@Model.Detalji" class="form-control" />
                <span asp-validation-for="Detalji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Snimi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Prikaz">Nazad na listu</a>
</div>