PomoćniProjekatGamingHub/Models/Igra/IgraDetaljiVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PomoćniProjekatGamingHub.Models.Igra
{
    public class IgraDetaljiVM
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Developer { get; set; }
        public string Izdavac { get; set; }
        public DateTime? DatumIzlaska { get; set; }
        public List<SelectListItem> IgraZarn { get; set; }
        public List<SelectListItem> IgraKonzola { get; set; }
        public string VideoLink { get; set; }
        public string SlikaLink { get; set; }
        public string YouTubeId
        {
            get
            {
                string id = null;

                if (!string.IsNullOrEmpty(VideoLink) &&
                   (VideoLink.Contains("youtube.com") || VideoLink.Contains("youtu.be")))
                {
                    int lastIndexOf = VideoLink.LastIndexOf("v=");
                    if (lastIndexOf == 0)
                    {
                        lastIndexOf = VideoLink.LastIndexOf("/") + 1;
                    }
                    else
                    {
                        lastIndexOf += 2;
                    }
                    id = VideoLink.Substring(lastIndexOf);
                }
                return id;
            }
        }



    }
}

PomoćniProjekatGamingHub/Models/Igra/IgraDodajVM.cs
using PomoćniProjekatGamingHub.EntityModels;
using PomoćniProjekatGamingHub.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PomoćniProjekatGamingHub.Models.Igra
{
    public class IgraDodajVM
    {
        public string Naziv { get; set; }
        public string Developer { get; set; }
        public string Izdavac { get; set; }
        public DateTime? DatumIzlaska { get; set; }
        public string VideoLink { get; set; }
        public string SlikaLink { get; set; }
        public int KonzolaId { get; set; }
        public List<IgraKonzola> Konzola { get; set; }
        public List<CheckBoxHelper> CheckBox { get; set; }
    }
}

PomoćniProjekatGamingHub/Models/Igra/IgraPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PomoćniProjekatGamingHub.Models
{
    public class IgraPrikazVM
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Developer { get; set; }
        public string Izdavac { get; set; }
        public DateTime? DatumIzlaska { get; set; }
        public string SlikaLink { get; set; }
    }
}

PomoćniProjekatGamingHub/Models/Igra/IgraUrediVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PomoćniProjekatGamingHub.Helpers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PomoćniProjekatGamingHub.Models
{
    public class IgraUrediVM
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Developer { get; set; }
        public string Izdavac { get; set; }
        public DateTime? DatumIzlaska { get; set; }
        public List<SelectListItem> IgraZarn { get; set; }
        public List<SelectListItem> IgraKonzola { get; set; }
        public string VideoLink { get; set; }
        public string SlikaLink { get; set; }
        public int KonzolaID { get; internal set; }
        public List<CheckBoxHelper> Konzola { get; set; }
    }
}

PomoćniProjekatGamingHub/Controllers/IgraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PomoćniProjekatGamingHub.EF;
using PomoćniProjekatGamingHub.EntityModels;
using PomoćniProjekatGamingHub.Helpers;
using PomoćniProjekatGamingHub.Models;
using PomoćniProjekatGamingHub.Models.Igra;

namespace PomoćniProjekatGamingHub.Controllers
{
    public class IgraController : Controller
    {
        MojDbContext db = new MojDbContext();
        public IActionResult Prikaz()
        {
            var m = db.Igra.Select(i => new IgraPrikazVM
            {
                Id=i.Id,
                Naziv = i.Naziv,
                DatumIzlaska = i.DatumIzlaska,
                Developer = i.Developer,
                Izdavac = i.Izdavac,
                SlikaLink = ImageHelper.GetImageBase64(i.SlikaLink)
            }).ToList();
            return View(m);
        }

        [HttpGet]
        public IActionResult Dodaj()
        {
            List<CheckBoxHelper> listaKonzola = new List<CheckBoxHelper>();

            listaKonzola = db.Konzola.Select(a => new CheckBoxHelper
            {
                Id = a.Id,
                Text = a.Naziv,
                IsChecked = false,
                KonzolaId = a.Id
            }).ToList();

            IgraDodajVM model = new IgraDodajVM
            {
                CheckBox = listaKonzola
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Dodaj(IgraDodajVM igra, IFormFile file)
        {
            Igra novaIgra = new Igra
            {
                Naziv = igra.Naziv,
                Developer = igra.Developer,
                Izdavac = igra.Izdavac,
                DatumIzlaska = igra.DatumIzlaska,
                VideoLink = igra.VideoLink,
                SlikaLink = ImageHelper.GetImageByteArray(file),
            };
            db.Igra.Add(novaIgra);
            db.SaveChanges();

            foreach (var item in igra.CheckBox)
            {
                IgraKonzola k = new IgraKonzola
                {
                    IgraID = novaIgra.Id,
                    KonzolaID = item.KonzolaId,
                    IsChecked = item.IsChecked
                };
                db.IgraKonzola.Add(k);
            }
            db.SaveChanges();
            return Redirect("/Igra/Prikaz");
        }

        [HttpGet]

        public IActionResult Uredi(int IgraID)
        {
            var igraIzBaze = db.Igra.Find(IgraID);

            IgraUrediVM m = new IgraUrediVM
            {
                Id = IgraID,
                Naziv = igraIzBaze.Naziv,
                Developer = igraIzBaze.Developer,
                Izdavac=igraIzBaze.Izdavac,
                DatumIzlaska = igraIzBaze.DatumIzlaska,
                VideoLink = igraIzBaze.VideoLink,
                SlikaLink = ImageHelper.GetImageBase64(igraIzBaze.SlikaLink),

                Konzola = db.IgraKonzola
                .Where(ik => ik.IgraID == IgraID)
                .Select(ik => new CheckBoxHelper
                {
                    Id = ik.ID,
                    Text = ik.Konzola.Naziv,
                    IsChecked = ik.IsChecked,
                    KonzolaId = ik.KonzolaID
                }).ToList()
            };
            return View(m);
        }
        public IActionResult Snimi(IgraUrediVM igra, IFormFile file)
        {

            Igra Igra = db.Igra.Find(igra.Id);
            Igra.Naziv = igra.Naziv;
            Igra.Developer = igra.Developer;
            Igra.Izdavac = igra.Izdavac;
            Igra.DatumIzlaska = igra.DatumIzlaska;
            Igra.VideoLink = igra.VideoLink;
            var novaSlika = ImageHelper.GetImageByteArray(file);
            if (novaSlika != null)
            {
                Igra.SlikaLink = novaSlika;
            }
            List<IgraKonzola> igraKonzola = db.IgraKonzola.Where(igraId => igraId.IgraID == igra.Id).ToList();
            foreach (var item in igraKonzola)
            {
                foreach (var i in igra.Konzola)
                {
                    if (item.ID == i.Id)
                    {
                        item.IsChecked = i.IsChecked;
                    }
                }
            }
            db.SaveChanges();
            return Redirect("/Igra/Prikaz");
        }
        public IActionResult Detalji(int IgraID)
        {
           var m = db.Igra.Where(i => i.Id == IgraID)
                    .Select(i => new IgraDetaljiVM
                    {
                        Id = i.Id,
                        Naziv = i.Naziv,
                        DatumIzlaska = i.DatumIzlaska,
                        Developer = i.Developer,
                        Izdavac = i.Izdavac,
                        VideoLink = i.VideoLink,
                        SlikaLink = ImageHelper.GetImageBase64(i.SlikaLink)
                    }).FirstOrDefault();

            return View(m);
        }

        public IActionResult Obrisi(int IgraID)
        {
            Igra igra = db.Igra.Find(IgraID);
            db.Remove(igra);
            List<IgraKonzola> iKonzole = db.IgraKonzola.Where(ik => ik.IgraID == IgraID).ToList();
            db.RemoveRange(iKonzole);
            List<IgraZarn> iZarnovi = db.IgraZarn.Where(iz => iz.IgraID == IgraID).ToList();
            db.RemoveRange(iZarnovi);

            db.SaveChanges();
            return Redirect("/Igra/Prikaz");
        }
    }
}

PomoćniProjekatGamingHub/Views/Igra/Detalji.cshtml
@model PomoćniProjekatGamingHub.Models.Igra.IgraDetaljiVM

@{
    ViewData["Title"] = "Detalji";
}

<h1>Detalji</h1>

<div>
    <h4>IgraDetaljiVM</h4>
    <hr />
    <dl class="row">
        @if (!string.IsNullOrEmpty(Model.YouTubeId))
        {
            <span> style="margin:0 0 0 20px">
                <iframe width="800" height="520"
                        src="https://www.youtube.com/embed/@Model.YouTubeId">
                </iframe>
            </span>
        }
        </dl>

        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Naziv)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Naziv)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Developer)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Developer)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Izdavac)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Izdavac)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DatumIzlaska)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DatumIzlaska)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.VideoLink)
            </dt>
            <dd class="col-sm-10">
                <a href="@Html.DisplayFor(model => model.VideoLink)" target="_blank">@Html.DisplayFor(model => model.VideoLink)</a>
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.SlikaLink)
            </dt>
            <dd class="col-sm-10">
                @if (!string.IsNullOrEmpty(Model.SlikaLink))
                {
                     <img src="@Model.SlikaLink" style="max-width:320px; max-height:520px" /> }
                else
                {
                     <img src="~/img/no-game.jpg" style="max-width:320px; max-height:520px" /> 
                }
             </dd>
        </dl>
</div>
<div id="ajaxDiv" style="border:1px solid red">

</div>
<script>
     function UcitajStavke() {
         $.get("/IgraZarn/Index?IgraID=@Model.Id", function (d) {
             $("#ajaxDiv").html(d);
        })
    }
    UcitajStavke();
    function StavkaObrisi(IgraZarnID) {
        $.get("/IgraZarn/Obrisi?IgraZarnID=" + IgraZarnID,
            function (d) {
                UcitajStavke();
            });
    }

    function StavkaDodaj(IgraID) {
        $.get("/IgraZarn/Dodaj?IgraID=" + IgraID,
            function (d) {
                $("#ajaxDiv").html(d);
            });
    }

    function StavkaSnimi() {
        var form = $("#IgraZarnForma");
        var url = "/IgraZarn/Snimi";
        $.ajax({
            type: "POST",
            url: url,
            data: form.serialize(),
            success: function (data) { UcitajStavke(); }
        });
    }


</script>

<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Prikaz">Natrag na listu</a>
</div>

PomoćniProjekatGamingHub/Views/Igra/Dodaj.cshtml
@model PomoćniProjekatGamingHub.Models.Igra.IgraDodajVM

@{
    ViewData["Title"] = "Dodaj";
}

<h1>Dodaj</h1>

<h4>IgraDodajVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Dodaj" asp-controller="Igra" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Developer" class="control-label"></label>
                <input asp-for="Developer" class="form-control" />
                <span asp-validation-for="Developer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Izdavac" class="control-label"></label>
                <input asp-for="Izdavac" class="form-control" />
                <span asp-validation-for="Izdavac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumIzlaska" class="control-label"></label>
                <input asp-for="DatumIzlaska" class="form-control" />
                <span asp-validation-for="DatumIzlaska" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoLink" class="control-label"></label>
                <input asp-for="VideoLink" class="form-control" />
                <span asp-validation-for="VideoLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SlikaLink" class="control-label"></label><br />
                @if (!string.IsNullOrEmpty(Model.SlikaLink))
                {
                    <img src="@Model.SlikaLink" style="max-width:100px; max-height:100px" />
                }
                <input asp-for="SlikaLink" type="file" name="file" id="file" />
                <span asp-validation-for="SlikaLink" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="KonzolaId" readonly hidden class="control-label">Konzole: </label>
                <input asp-for="KonzolaId" readonly hidden class="form-control" />
                <span asp-validation-for="KonzolaId" class="text-danger"></span>
            </div>
            <div>
                @for (int i = 0; i < Model.CheckBox.Count; i++)
                {
                    <label>@Model.CheckBox[i].Text</label>
                    <input type="checkbox" asp-for="@Model.CheckBox[i].IsChecked" />
                    <input type="hidden" asp-for="@Model.CheckBox[i].KonzolaId" />

                }
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Prikaz">Natrag</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PomoćniProjekatGamingHub/Views/Igra/Prikaz.cshtml
@using PomoćniProjekatGamingHub.EntityModels
@model List<IgraPrikazVM>

<h1>Igre</h1>
<a href="/Igra/Dodaj" class="btn btn-success">Dodaj</a>

<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Slika</th>
            <th>Naziv</th>
            <th>Izdavac</th>
            <th>Developer</th>
            <th>Datum Izlaska</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (IgraPrikazVM i in Model)
        {
        <tr>
            <td>@i.Id</td>
            <td>
                @if (!string.IsNullOrEmpty(i.SlikaLink))
                {
                    <img src="@i.SlikaLink" style="max-width:100px; max-height:100px" />
                }
                else
                {
                    <img src="~/img/no-game.jpg" style="max-width:100px; max-height:100px" />
                }
            </td>
            <td>@i.Naziv</td>
            <td>@i.Izdavac</td>
            <td>@i.Developer</td>
            <td>@(i.DatumIzlaska?.ToString("dd.MM.yyyy"))</td>
            <td>
                <a href="/Igra/Detalji?IgraID=@i.Id" class="btn btn-primary">Detalji</a> |
                <a href="/Igra/Uredi?IgraID=@i.Id" class="btn btn-primary">Uredi</a> |
                <a href="/Igra/Obrisi?IgraID=@i.Id" class="btn btn-danger">Obrisi</a>
            </td>
        </tr>
        }

    </tbody>
</table>

PomoćniProjekatGamingHub/Views/Igra/Uredi.cshtml
@model PomoćniProjekatGamingHub.Models.IgraUrediVM

@{
    ViewData["Title"] = "Dodaj";
}

<h1>Dodaj</h1>

<h4>IgraDodajVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Snimi" asp-controller="Igra" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Developer" class="control-label"></label>
                <input asp-for="Developer" class="form-control" />
                <span asp-validation-for="Developer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Izdavac" class="control-label"></label>
                <input asp-for="Izdavac" class="form-control" />
                <span asp-validation-for="Izdavac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumIzlaska" class="control-label"></label>
                <input asp-for="DatumIzlaska" class="form-control" />
                <span asp-validation-for="DatumIzlaska" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoLink" class="control-label"></label>
                <input asp-for="VideoLink" class="form-control" />
                <span asp-validation-for="VideoLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SlikaLink" class="control-label"></label><br />
                @if (!string.IsNullOrEmpty(Model.SlikaLink))
                {
                    <img src="@Model.SlikaLink" style="max-width:100px; max-height:100px" />
                }
                <input asp-for="SlikaLink" type="file" name="file" id="file" />
                <span asp-validation-for="SlikaLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Snimi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Prikaz">Natrag na listu</a>
</div>