PomoćniProjekatGamingHub/Models/Zarn/ZarnPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PomoćniProjekatGamingHub.Models.Zarn
{
    public class ZarnPrikazVM
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
    }
}

PomoćniProjekatGamingHub/Models/Zarn/ZarnUrediVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PomoćniProjekatGamingHub.Models.Zarn
{
    public class ZarnUrediVM
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
    }
}

PomoćniProjekatGamingHub/Controllers/ZarnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PomoćniProjekatGamingHub.EF;
using PomoćniProjekatGamingHub.EntityModels;
using PomoćniProjekatGamingHub.Models.Zarn;

namespace PomoćniProjekatGamingHub.Controllers
{
    public class ZarnController : Controller
    {
        MojDbContext db = new MojDbContext();
        public IActionResult Prikaz()
        {
            var zarnovi = db.Zarn
                .Select(z => new ZarnPrikazVM
                {
                    Id = z.Id,
                    Naziv = z.Naziv,
                    Opis = z.Opis
                }).ToList();

            return View(zarnovi);
        }
        public IActionResult Uredi(int ZarnID)
        {
            ZarnUrediVM zarn;
            if (ZarnID == 0)
            {
                zarn = new ZarnUrediVM() { };
            }
            else
            {
                zarn = db.Zarn.Where(z => z.Id == ZarnID)
                .Select(z => new ZarnUrediVM
                {
                    Id = z.Id,
                    Naziv = z.Naziv,
                    Opis = z.Opis
                }).Single();
            }

            return View(zarn);
        }
        public IActionResult Snimi(ZarnUrediVM z)
        {
            Zarn zarn;
            if (z.Id == 0)
            {
                zarn = new Zarn();
                db.Add(zarn);
            }
            else
            {
                zarn = db.Zarn.Find(z.Id);
            }
            zarn.Naziv = z.Naziv;
            zarn.Opis = z.Opis;

            db.SaveChanges();
            return Redirect("/Zarn/Prikaz");
        }
        public IActionResult Obrisi(int ZarnID)
        {
            Zarn z = db.Zarn.Find(ZarnID);
            db.Remove(z);
            db.SaveChanges();
            return Redirect("/Zarn/Prikaz");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

PomoćniProjekatGamingHub/Views/Zarn/Prikaz.cshtml
@using PomoćniProjekatGamingHub.Models.Zarn

@model List<ZarnPrikazVM>

<h1>Zarnovi</h1>
<a href="/Zarn/Uredi" class="btn btn-success">Dodaj</a>
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Opis</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (ZarnPrikazVM z in Model)
        {
            <tr>
                <td>@z.Naziv</td>
                <td>@z.Opis</td>
                <td>
                    <a href="/Zarn/Uredi?ZarnID=@z.Id" class="btn btn-primary">Uredi</a>
                    <a href="/Zarn/Obrisi?ZarnID=@z.Id" class="btn btn-danger">Obrisi</a>
                </td>
            </tr>
        }

    </tbody>
</table>

PomoćniProjekatGamingHub/Views/Zarn/Uredi.cshtml
@model PomoćniProjekatGamingHub.Models.Zarn.ZarnUrediVM

<h1>UrediZarn</h1>

<h4>Zarn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Snimi" asp-controller="Zarn">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" readonly style="display:none">
                <label>ZarnID</label>
                <input name="Id" value="@Model.Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Naziv"  class="control-label"></label>
                <input asp-for="Naziv" value=@Model.Naziv class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" value=@Model.Opis class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Snimi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Prikaz">Nazad na listu</a>
</div>